Fix serverless deployment
guidesmiths/bamboohrbot pull request #16
Opened 2023-02-15 14:35 UTC by inigomarquinez

### Main changes

- fix: add AWS_ACCOUNT_ID to serverless environment

2023-02-15 15:03 UTC, w3dani requested changes
Have a look to this -> https://www.serverless.com/framework/docs/providers/aws/guide/variables#referencing-aws-specific-variables

2023-02-15 15:59 UTC, inigomarquinez commented
> Have a look to this -> https://www.serverless.com/framework/docs/providers/aws/guide/variables#referencing-aws-specific-variables

@w3dani , let me know if it's ok now

2023-02-15 16:35 UTC, w3dani requested changes

2023-02-15 16:35 UTC, w3dani commented on serverless.yml
>        Resource: 'arn:aws:secretsmanager:${self:provider.region}:${self:provider.environment.AWS_ACCOUNT_ID}:*'
here you can replace those values as well

2023-02-16 10:12 UTC, w3dani requested changes

2023-02-16 10:12 UTC, w3dani commented on serverless.yml
> +      Resource: 'arn:aws:secretsmanager:${self:provider.region}:${aws:accountId}:*'
`${self:provider.region}` -> `${aws:region}`

2023-02-16 14:29 UTC, inigomarquinez commented on serverless.yml
> +      Resource: 'arn:aws:secretsmanager:${self:provider.region}:${aws:accountId}:*'
Done

2023-02-16 14:56 UTC, w3dani approved these changes
<img src="https://media3.giphy.com/media/AuwBPJztsEWkw/giphy.gif"/>

2023-02-17 12:20 UTC, merged